In [26]:
!open .

In [39]:
import pyopt

In [37]:
!pip install pyOpt

![](3.0.png)
![](3.1.png)
![](3.2.png)

In [3]:
from scipy.optimize import linprog
from numpy import *

In [7]:
c = array([34 - 22 - 2*2 - 1*2, 30 - 18 - 2 - 3])
A = array([[2,1],[2,3]])
b = [40,60]

linprog(-c,A,b)

 message: 'Optimization terminated successfully.'
 success: True
     nit: 2
     fun: -160.0
   slack: array([ 0.,  0.])
  status: 0
       x: array([ 15.,  10.])

![](4.png)

In [22]:
A = array([[20,18,25], [12,11,33], [17, 17, 40]])
A

array([[20, 18, 25],
       [12, 11, 33],
       [17, 17, 40]])

In [23]:
b = array([15,10,10])
b

array([15, 10, 10])

In [25]:
c = array([24, 6, 11])
c

array([24,  6, 11])

<module 'pyopt' from '/Users/mmngreco/anaconda/envs/py3/lib/python3.4/site-packages/pyopt/__init__.py'>