In [1]:
%load_ext rpy2.ipython

In [2]:
import scipy.optimize as op
import numpy as np

In [3]:
%%R
# PROBLEMA DEL TRANSPORTE
library(lpSolve)

obj=c(5,7)
res = matrix(c(8,14,10,4), nrow=2, byrow=T)
dir = c(rep('<=', 2))
b = c(63,45)

A = lp(direction='max', 
       obj,             # coeficientes de la funcion objetivo
       res,             # coeficientes de las restricciones del lado izquierdo
       dir,             # desigualdad
       b,               # restricciones del lado derecho
       int.vec=c(1,2),  # variables enteras.
       all.int=T)       # todos los resultados enteros
print(A)
print(A$solution)

Success: the objective function is 31 
[1] 2 3


In [42]:
%%R
# PROBLEMA DEL TRANSPORTE
require(lpSolve)

A = lp.transport(cost.mat=matrix(c(10,30,15,8,12,25,5,35,20,7,14,22), nrow=3,byrow=T), # matrix de costes ij: desde i a j
                 direction='min', # minimizar o maximizar
                 row.signs=c(rep('=', 3)),  # vector de desigualdades de las restricciones de filas
                 row.rhs=c(50,20,40),       # vector de las restricciones del lado derecho de las filas
                 col.signs=c(rep('=', 4)),  # vector de desigualdades de las columnas
                 col.rhs=c(35,35,22,18),    # vector de las restricciones columnas.
                 integers=NULL)             # vector que representa que variables tienen que ser enteras. null=ninguna
print(A)
print(A$solution)

Success: the objective function is 897 
     [,1] [,2] [,3] [,4]
[1,]   32    0    0   18
[2,]    0    0   20    0
[3,]    3   35    2    0


In [5]:
%%R
# PROBLEMA DEL TRANSPORTE
require(lpSolve)

A = lp.assign(cost.mat=matrix(c(34,10,15,28,16,15,22,12,10,25,13,20,30,19,27,31), nrow=4,byrow=T), # matrix de costes ij: desde i a j
              direction='min') # minimizar o maximizar
print(A)
print(A$solution)

Success: the objective function is 56 
     [,1] [,2] [,3] [,4]
[1,]    0    0    1    0
[2,]    0    0    0    1
[3,]    1    0    0    0
[4,]    0    1    0    0


![](9.png)

$x_i$ = {0: si no selecciono proyecto, 1: si selecciono el proyecto} $\forall i=1,...6$

El valor de cada pryecto es $v_i·x_i$

El objetivo es:

$Max\ \sum_1^6{v_ix_i}$

El coste es $c_{ij} \forall i=1,..6 \, \ j=1,...,3$
Por tanto el gasto es:

$c_{ij}x_i ≤ d_j\ \forall\ x_j$

$x_i \epsilon {0,1}$


## POR TANTO: 

$Max\ \sum_1^6{v_ix_i}$

s.a.

$c_{ij}x_i ≤ d_j \ \forall\ x_j$

$x_i\ \epsilon\ \{0,1\}$

In [5]:
# datos

p = list(range(1,7))
vpn = [50, 40, 30, 40, 50, 60]
year1 = [10, 20] * 3
year2 = [15,10] * 3
year3 = [10,5] * 3
disp = [75, 70, 35]

In [6]:
mcost = [year1, year2, year3]
mcost = np.array(mcost).T
mcost = list(map(list, mcost))

In [7]:
%%R -i mcost,disp,vpn

require(lpSolve)

fobj = vpn
resdir = rep('<=', 3)
res = mcost
resbnd = disp

A = lp('max',
       fobj,
       res,
       resdir,
       resbnd,
       all.bin=T)
print(A)
print(A$solution)

/Users/mmngreco/Virtualenvs/ipynb/lib/python3.5/site-packages/rpy2/robjects/functions.py:106: UserWarning: Loading required package: lpSolve

  res = super(Function, self).__call__(*new_args, **new_kwargs)


Success: the objective function is 200 
[1] 1 1 0 0 1 1



![](11.png)

In [19]:
c = [12, 8, 7, 5, 8, 7, 7, 8, 10, 8, 13, 6, 7, 9, 14, 15, 8, 7, 6, 12, 10, 8, 9, 13, 7, 9, 13, 14, 8, 8, 11, 11]
k = [100, 150, 100, 150]
k = np.array(k).reshape(1,4)
n = len(c)
c = np.array(c).reshape(4,8).T
fobj = np.vstack((c,k))
res = np.repeat(1, n).reshape(n, 1)
#resbnd = 

bin_vec = list(range(n - 4 + 1, n + 1))
fobj

array([[ 12,  10,   8,   7],
       [  8,   8,   7,   9],
       [  7,  13,   6,  13],
       [  5,   6,  12,  14],
       [  8,   7,  10,   8],
       [  7,   9,   8,   8],
       [  7,  14,   9,  11],
       [  8,  15,  13,  11],
       [100, 150, 100, 150]])

In [91]:
%%R -i fobj,n,res,resbnd,bin_vec

require(lpSolve)

fobj = obj
resdir = rep('<=', n)
res = mcost
resbnd = disp

A = lp('min',
       fobj,
       res,
       resdir,
       resbnd,
       all.bin=T)

print(A)
print(A$solution)

Success: the objective function is 200 
[1] 1 1 0 0 1 1
